version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    branches:
      only:
        - source
    working_directory: ~/hugo
    steps:
    # working_directoryにリポジトリをコピー
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "91:db:bd:a8:04:a0:13:5a:2c:74:5f:a9:18:fc:82:74"
    - run:
        name: Machine login
        command: echo "machine github.com\nlogin $GITHUB_TOKEN" > ~/.netrc
    - run:
      # 作業ブランチをsourceに切り替え
        name: Checkout branch
        command: git checkout source
    - run:
      # submoduleにしているテーマのアップデート
        name: Update theme
        command: git submodule update -i
    - run:
      # 記事の作成
        name: Create ariticle
        command: hugo
    - run:
      # tmpフォルダにmasterブランチをclone
        name: Clone master into tmp
        command: mkdir -p tmp && cd tmp && git clone https://hsrmy@github.com/hsrmy/hsrmy.github.io.git
    - run:
      # 一旦tmp/hsrmy.github.ioの中身を削除
        name: Clean tmp/hsrmy.github.io
        command: rm -rf tmp/hsrmy.github.io/*
    - run:
      # publicの中身をtmp/hsrmy.github.ioの中にコピー
        name: Copy public
        command: cp -fr public/* tmp/hsrmy.github.io/
    - run:
      # Gitの設定
        name: Setting git
        command: git config --global user.name hsrmy && git config --global user.email hsrmy@emradc.xyz
    - run:
      # 環境変数のセット
        name: Set environment variables
        command: echo 'export MSG=$(git diff --name-only source|grep content|sed -z 's/\n/ /g')' >> $BASH_ENV && echo $BASH_ENV
    - run:
      # Commit
        name: Commit
        command: cd tmp/hsrmy.github.io/ && git fetch && git add . && git commit -m "Add ${MSG}"
    - run:
      # Push
        name: Push
        command: cd tmp/hsrmy.github.io/ && git push origin master
